# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - clear
      - goreleaser build --snapshot --clean
      - tree dist
    silent: true

  install:
    desc: Install vja binary to $GOPATH/bin
    cmds:
      - go install ./cmd/vja
    silent: false
